name: Publish changes to GH pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install, build & deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci && npm run ng -- deploy --base-href=/perruche/ --repo=https://github.com/vladtheimpala/perruche.git --name="vladtheimpala" --email=negus1309@gmail.com
