name: Publish changes to GH pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build & deploy
        run: ng deploy --base-href=/perruche/
